services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/permisyn
      NODE_ENV: development
      PORT: 5000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:5173"
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    env_file:
      - ./backend/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
